#!/bin/bash

#echo "Translation to SAT..."
./mci2sat -r "$2" $1.mci

#echo "SAT checking..."
minisat $1.sat $1.res > /dev/null

#echo "Evaluating SAT..."
./sateval -data -r $1.mci $1.res

sateval=$?
#echo "Sateval is: $sateval"

exit $sateval

#rm -f $1.mci $1.sat $1.res