#!/bin/bash

#echo "Translation to SAT..."
if [ -f $1.mci ]; then
  src/mci2sat -r "$2" $1.mci
  correct=$?
else
  echo "mci file does not exist"
  correct=0
fi
#echo $correct
if [ $correct -eq 1 ]; then 
  #echo "SAT checking..."
  minisat $1.sat $1.res > /dev/null

  #echo "Evaluating SAT..."
  src/sateval -r $1.mci $1.res

  sateval=$?
else
  sateval=$correct
fi

#echo "Sateval is: $sateval"
exit $sateval

#rm -f $1.mci $1.sat $1.res