#!/bin/bash

echo "Unfolding..."
if [ -f $1.ll_net ]; then
  ./ecofolder $1.ll_net
else
  ./ecofolder $1.ll
fi

echo "Translation to SAT..."
./mci2sat -r "$2" $1_unf.mci

echo "SAT checking..."
minisat $1_unf.sat $1_unf.res > /dev/null

echo "Evaluating SAT..."
./sateval -r $1_unf.mci $1_unf.res

echo "Converting to dot..."
./mci2dot -c $1_unf.mci $1_unf.evco > $1_unf.dot

echo "Producing the pdf..."
dot -T pdf $1_unf.dot > $1_unf.pdf

echo "Displaying the pdf..."
evince $1_unf.pdf


#rm -f $1.mci $1.sat $1.res
