#!/bin/bash

# echo "Unfolding..."
# if [ -f $1.ll_net ]; then
#   ./ecofolder -q $2 -r 0 $1.ll_net
# else
#   ./ecofolder -q $2 -r 0 $1.ll
# fi
#../ecofolder/ecofolder

#free=$?

#echo $free

echo "Converting to dot..."
#./mci2dot $1_unf.mci > $1_unf.dot
./mci2dot_ev -r 0 -c -p $1_unf.mci $2.evev > $1_unf.dot

# if the compressed mode is needed, you should run:
#./mci2dot_cpr $1_unf.mci > $1_unf.dot

# if the event structure is needed, you should run:
#./mci2dot_ev $1_unf.mci > $1_unf.dot

echo "Producing the pdf..."
dot -T pdf $1_unf.dot > $1_unf.pdf

echo "Displaying the pdf..."
evince $1_unf.pdf

# Deleting files...
#rm -f $1.ll_net $1.dot $1.pdf $1.mci
#rm -f $1.ll_net $1.dot $1.mci